
SET(GLFW_ROOT_PATH F:/dok/kode/libraries/glfw-2.7.2/ )


FIND_PATH( GLFW_INCLUDE_DIR NAMES GL/glfw.h 
		PATHS ${GLFW_ROOT_PATH}/include
	)

FIND_LIBRARY( GLFW_STATIC_DEBUG_LIBRARY NAMES glfw
		PATHS ${GLFW_ROOT_PATH}/bin/lib-msvc100/debug
	) 

FIND_LIBRARY( GLFW_STATIC_RELEASE_LIBRARY NAMES glfw
		PATHS ${GLFW_ROOT_PATH}/bin/lib-msvc100/release
	) 
