
SET(GLFW_ROOT_PATH F:/dok/kode/libraries/glfw-2.7.5 )


FIND_PATH( GLFW_INCLUDE_DIR NAMES GL/glfw.h 
		PATHS ${GLFW_ROOT_PATH}/include
	)

FIND_LIBRARY( GLFW_STATIC_DEBUG_LIBRARY NAMES glfw
		PATHS ${GLFW_ROOT_PATH}/lib-msvc100
	) 

FIND_LIBRARY( GLFW_STATIC_RELEASE_LIBRARY NAMES glfw
		PATHS ${GLFW_ROOT_PATH}/lib-msvc100
	) 
