
SET(PROTOWIZARD_ROOT_PATH F:/gitrepos/ProtoWizard)


FIND_PATH( PROTOWIZARD_INCLUDE_DIR NAMES protographics.h 
	PATHS  ${PROTOWIZARD_ROOT_PATH} 
	)

FIND_LIBRARY( PROTOWIZARD_LIB NAMES protowizard
	PATHS ${PROTOWIZARD_ROOT_PATH}/lib
	) 